import {useEffect,useMemo,useRef,useState} from 'react';
import {FolderScene,type FolderHandle} from './FolderScene';
import {imageUrl,type Portfolio,type Project} from './types';

function Behance(){return <a className="creator-link" href="https://www.behance.net/KethanArtzz" target="_blank" rel="noopener noreferrer" aria-label="Kethan Artzz on Behance"><span className="behance-mark" aria-hidden="true">Bē</span><span>Behance<small>More from the studio</small></span><span aria-hidden="true">↗</span></a>;}
function ArtBackdrop(){return <div className="art-backdrop" aria-hidden="true"><div className="paper-grain"/><svg viewBox="0 0 1440 900" preserveAspectRatio="xMidYMid slice"><g className="brush-lines" fill="none" stroke="currentColor"><path d="M-90 620C140 160 75 590 298 220S50 650 345 350" strokeWidth="3"/><path d="M-70 644C165 190 94 610 305 240" strokeWidth=".8"/><path d="M1190 660Q1090 440 1360 190M1220 710L1480 230" strokeWidth="1"/></g><g className="type-study" fill="currentColor"><text x="1150" y="340" fontFamily="Georgia,serif" fontSize="170">Aa</text><text x="90" y="785" fontFamily="monospace" fontSize="10" letterSpacing="6">FORM / SPACE / STORY</text></g><g className="design-guides" stroke="currentColor" fill="none" strokeWidth=".7"><circle cx="1200" cy="660" r="82"/><path d="M1080 660H1320M1200 540V780M88 180H325M110 154V210M295 154V210"/><path d="M1140 720L1260 600M1136 596H1264V724H1136Z" strokeDasharray="4 8"/></g></svg></div>;}
function Contact({content}:{content:Portfolio['details']}){
  const [status,setStatus]=useState(''),[sending,setSending]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(sending)return;setSending(true);setStatus('Sending your note…');
    try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');form.reset();setStatus('Your message is in the studio inbox. Thank you for reaching out.');}catch(error){setStatus(error instanceof Error?error.message:'Unable to send. Please try again.');}finally{setSending(false);}
  }
  return <section id="contact" className="contact"><div><span className="eyebrow">Start a conversation</span><h2>{content.contactTitle}</h2><p>{content.contactIntro}</p><Behance/></div><form onSubmit={submit}><div className="form-pair"><label>Name<input name="name" required maxLength={100} autoComplete="name" placeholder="Your name"/></label><label>Email<input name="email" required type="email" maxLength={254} autoComplete="email" placeholder="you@studio.com"/></label></div><label>Regarding<input name="subject" required maxLength={180} placeholder="A project, collaboration, or idea"/></label><label>Message<textarea name="message" required maxLength={8000} rows={5} placeholder="Tell me a little about it…"/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><div className="form-bottom"><button type="submit" disabled={sending}>{sending?'Sending…':content.contactButton||'Send message'} <span aria-hidden="true">↗</span></button><p role="status">{status}</p></div></form></section>;
}
export function Preview({project,onClose,label}:{project:Project;onClose:()=>void;label:string}){
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const node=dialog.current!;const scope=node.getRootNode() as Document|ShadowRoot;const previous=scope.activeElement as HTMLElement|null;node.showModal();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{node.close();document.body.style.overflow=prior;previous?.focus?.({preventScroll:true});};},[]);
  return <dialog ref={dialog} className="project-dialog" onCancel={event=>{event.preventDefault();onClose();}} onClick={event=>{if(event.target===event.currentTarget)onClose();}} aria-labelledby="project-title"><div className="project-inner"><button className="close-preview" onClick={onClose} aria-label="Close project">×</button><div className="preview-image"><img src={imageUrl(project,true)} alt={project.title}/></div><div className="preview-copy"><span className="eyebrow">{project.cat}</span><h2 id="project-title">{project.title}</h2><p>{project.description}</p><ul className="tags">{project.technologies.map((technology,i)=><li key={i}>{technology}</li>)}</ul>{project.link&&<a className="project-link" href={project.link} target="_blank" rel="noopener noreferrer">{label||'View project'} ↗</a>}<button className="return-link" onClick={onClose}>Return to the collection</button></div></div></dialog>;
}
export default function App(){
  const [data,setData]=useState<Portfolio|null>(null),[error,setError]=useState(''),[folder,setFolder]=useState(''),[page,setPage]=useState(0),[state,setState]=useState('closed'),[preview,setPreview]=useState<Project|null>(null),[webglError,setWebglError]=useState(false);
  const scene=useRef<FolderHandle>(null);
  useEffect(()=>{const controller=new AbortController();fetch('/api/portfolio',{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error('The collection could not be loaded.');return response.json();}).then((portfolio:Portfolio)=>{setData(portfolio);setFolder(portfolio.folders[0]||'');document.title=portfolio.details.creatorName+' · '+portfolio.details.portfolioTitle;}).catch(error=>{if(error.name!=='AbortError')setError(error.message);});return()=>controller.abort();},[]);
  const collection=useMemo(()=>data?.images.filter(project=>project.cat===folder)||[],[data,folder]);
  const projects=useMemo(()=>collection.slice(page*5,page*5+5),[collection,page]);
  if(!data)return <main className="loading"><span className="wordmark">KA</span><p role="status">{error||'Opening the archive…'}</p>{error&&<button onClick={()=>location.reload()}>Try again</button>}</main>;
  const content=data.details,closed=state==='closed';
  const closePreview=()=>{if(webglError)setPreview(null);else scene.current?.restore();};
  return <><ArtBackdrop/><header className="site-header"><a className="wordmark" href="#work" aria-label={content.creatorName+' home'}>KA<span>{content.creatorName}</span></a><nav aria-label="Main navigation"><a href="#work">Selected work</a><a href="#contact">Let’s talk <span aria-hidden="true">↗</span></a></nav></header>
    <main><section id="work" className="work"><div className="work-heading"><span className="eyebrow">An independent creative archive</span><h1>{content.portfolioTitle}</h1><p>{content.tagline}</p></div><div className="folder-picker" aria-label="Project folders">{data.folders.map(name=><button key={name} aria-pressed={folder===name} disabled={!closed&&!webglError} onClick={()=>{setFolder(name);setPage(0);}}>{name}</button>)}</div>
      <div className="scene-wrap">{projects.length>0&&!webglError?<FolderScene key={folder+'-'+page} ref={scene} projects={projects} onState={setState} onPreview={setPreview} onError={()=>setWebglError(true)}/>:<div className="scene-empty"><p>{webglError?'Use the project list below to explore this collection.':'This folder is waiting for its first project.'}</p></div>}
      <div className="scene-caption"><p className="scene-hint" role="status">{state==='closed'?'A few ideas, filed together.':state==='open'?'Pick a card. Take a closer look.':state==='opening'?'Unfolding the collection…':state==='closing'?'Putting everything back in place.':''}</p>{projects.length>0&&!webglError&&<button className="folder-toggle" disabled={state==='preview'||state==='restoring'} onClick={()=>scene.current?.toggle()}>{state==='closed'||state==='closing'?content.openLabel||'Open folder':content.closeLabel||'Close folder'} <span aria-hidden="true">{closed?'+':'−'}</span></button>}</div></div>
      <div className="collection-notes"><p>{content.portfolioIntro}</p><span>{String(projects.length).padStart(2,'0')} / {folder}</span></div>
      {(state==='open'||webglError)&&<ol className="project-index" aria-label="Projects">{projects.map((project,i)=><li key={project.id||project.slug}><button onClick={()=>webglError?setPreview(project):scene.current?.select(i)}><span>0{i+1}</span>{project.title}<span aria-hidden="true">↗</span></button></li>)}</ol>}
      {collection.length>5&&<div className="page-controls"><button disabled={!closed||page===0} onClick={()=>setPage(page-1)}>Previous five</button><span>{page+1} / {Math.ceil(collection.length/5)}</span><button disabled={!closed||(page+1)*5>=collection.length} onClick={()=>setPage(page+1)}>Next five</button></div>}
    </section><Contact content={content}/></main><footer><span>© {new Date().getFullYear()} {content.creatorName}</span><span>Art direction · Design · Visual stories</span><a href="https://www.behance.net/KethanArtzz" target="_blank" rel="noopener noreferrer">Bē / Behance ↗</a></footer>{preview&&<Preview project={preview} onClose={closePreview} label={content.projectLabel}/>}</>;
}
